[MeasureAudio]
Measure=Plugin
Plugin=AudioLevel
Port=Output
FFTSize=#FFTSize#
FFTAttack=#FFTAttack#
FFTDecay=#FFTDecay#
Bands=90
Sensitivity=#Sensitivity#

[MeasureBand0]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1

[MeasureBand1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1

[MeasureBand2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2

[MeasureBand3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3

[MeasureBand4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4

[MeasureBand5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5

[MeasureBand6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6

[MeasureBand7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7

[MeasureBand8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8

[MeasureBand9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9

[MeasureBand10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10

[MeasureBand11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11

[MeasureBand12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12

[MeasureBand13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13

[MeasureBand14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14

[MeasureBand15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15

[MeasureBand16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16

[MeasureBand17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17

[MeasureBand18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18

[MeasureBand19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19

[MeasureBand20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20

[MeasureBand21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21

[MeasureBand22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22

[MeasureBand23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23

[MeasureBand24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24

[MeasureBand25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25

[MeasureBand26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26

[MeasureBand27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27

[MeasureBand28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28

[MeasureBand29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29

[MeasureBand30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30

[MeasureBand31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31

[MeasureBand32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32

[MeasureBand33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33

[MeasureBand34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34

[MeasureBand35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35

[MeasureBand36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36

[MeasureBand37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37

[MeasureBand38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38

[MeasureBand39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39

[MeasureBand40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40

[MeasureBand41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41

[MeasureBand42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42

[MeasureBand43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43

[MeasureBand44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44

[MeasureBand45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45

[MeasureBand46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46

[MeasureBand47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47

[MeasureBand48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48

[MeasureBand49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49

[MeasureBand50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50

[MeasureBand51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51

[MeasureBand52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52

[MeasureBand53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53

[MeasureBand54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54

[MeasureBand55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55

[MeasureBand56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56

[MeasureBand57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57

[MeasureBand58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58

[MeasureBand59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59

[MeasureBand60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60

[MeasureBand61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61

[MeasureBand62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62

[MeasureBand63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63

[MeasureBand64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=64

[MeasureBand65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=65

[MeasureBand66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=66

[MeasureBand67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=67

[MeasureBand68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=68

[MeasureBand69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=69

[MeasureBand70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=70

[MeasureBand71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=71

[MeasureBand72]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=72

[MeasureBand73]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=73

[MeasureBand74]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=74

[MeasureBand75]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=75

[MeasureBand76]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=76

[MeasureBand77]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=77

[MeasureBand78]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=78

[MeasureBand79]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=79

[MeasureBand80]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=80

[MeasureBand81]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=81

[MeasureBand82]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=82

[MeasureBand83]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=83

[MeasureBand84]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=84

[MeasureBand85]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=85

[MeasureBand86]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=86

[MeasureBand87]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=87

[MeasureBand88]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=88

[MeasureBand89]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=89

[MeasureBand90]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=90

[MeasureCalc]
Measure=Calc
Formula=1

[MeasureColor0]
Measure=Calc
Formula=MeasureBand0*#ColorInt#

[MeasureColor1]
Measure=Calc
Formula=MeasureBand1*#ColorInt#

[MeasureColor2]
Measure=Calc
Formula=MeasureBand2*#ColorInt#

[MeasureColor3]
Measure=Calc
Formula=MeasureBand3*#ColorInt#

[MeasureColor4]
Measure=Calc
Formula=MeasureBand4*#ColorInt#

[MeasureColor5]
Measure=Calc
Formula=MeasureBand5*#ColorInt#

[MeasureColor6]
Measure=Calc
Formula=MeasureBand6*#ColorInt#

[MeasureColor7]
Measure=Calc
Formula=MeasureBand7*#ColorInt#

[MeasureColor8]
Measure=Calc
Formula=MeasureBand8*#ColorInt#

[MeasureColor9]
Measure=Calc
Formula=MeasureBand9*#ColorInt#

[MeasureColor10]
Measure=Calc
Formula=MeasureBand10*#ColorInt#

[MeasureColor11]
Measure=Calc
Formula=MeasureBand11*#ColorInt#

[MeasureColor12]
Measure=Calc
Formula=MeasureBand12*#ColorInt#

[MeasureColor13]
Measure=Calc
Formula=MeasureBand13*#ColorInt#

[MeasureColor14]
Measure=Calc
Formula=MeasureBand14*#ColorInt#

[MeasureColor15]
Measure=Calc
Formula=MeasureBand15*#ColorInt#

[MeasureColor16]
Measure=Calc
Formula=MeasureBand16*#ColorInt#

[MeasureColor17]
Measure=Calc
Formula=MeasureBand17*#ColorInt#

[MeasureColor18]
Measure=Calc
Formula=MeasureBand18*#ColorInt#

[MeasureColor19]
Measure=Calc
Formula=MeasureBand19*#ColorInt#

[MeasureColor20]
Measure=Calc
Formula=MeasureBand20*#ColorInt#

[MeasureColor21]
Measure=Calc
Formula=MeasureBand21*#ColorInt#

[MeasureColor22]
Measure=Calc
Formula=MeasureBand22*#ColorInt#

[MeasureColor23]
Measure=Calc
Formula=MeasureBand23*#ColorInt#

[MeasureColor24]
Measure=Calc
Formula=MeasureBand24*#ColorInt#

[MeasureColor25]
Measure=Calc
Formula=MeasureBand25*#ColorInt#

[MeasureColor26]
Measure=Calc
Formula=MeasureBand26*#ColorInt#

[MeasureColor27]
Measure=Calc
Formula=MeasureBand27*#ColorInt#

[MeasureColor28]
Measure=Calc
Formula=MeasureBand28*#ColorInt#

[MeasureColor29]
Measure=Calc
Formula=MeasureBand29*#ColorInt#

[MeasureColor30]
Measure=Calc
Formula=MeasureBand30*#ColorInt#

[MeasureColor31]
Measure=Calc
Formula=MeasureBand31*#ColorInt#

[MeasureColor32]
Measure=Calc
Formula=MeasureBand32*#ColorInt#

[MeasureColor33]
Measure=Calc
Formula=MeasureBand33*#ColorInt#

[MeasureColor34]
Measure=Calc
Formula=MeasureBand34*#ColorInt#

[MeasureColor35]
Measure=Calc
Formula=MeasureBand35*#ColorInt#

[MeasureColor36]
Measure=Calc
Formula=MeasureBand36*#ColorInt#

[MeasureColor37]
Measure=Calc
Formula=MeasureBand37*#ColorInt#

[MeasureColor38]
Measure=Calc
Formula=MeasureBand38*#ColorInt#

[MeasureColor39]
Measure=Calc
Formula=MeasureBand39*#ColorInt#

[MeasureColor40]
Measure=Calc
Formula=MeasureBand40*#ColorInt#

[MeasureColor41]
Measure=Calc
Formula=MeasureBand41*#ColorInt#

[MeasureColor42]
Measure=Calc
Formula=MeasureBand42*#ColorInt#

[MeasureColor43]
Measure=Calc
Formula=MeasureBand43*#ColorInt#

[MeasureColor44]
Measure=Calc
Formula=MeasureBand44*#ColorInt#

[MeasureColor45]
Measure=Calc
Formula=MeasureBand45*#ColorInt#

[MeasureColor46]
Measure=Calc
Formula=MeasureBand46*#ColorInt#

[MeasureColor47]
Measure=Calc
Formula=MeasureBand47*#ColorInt#

[MeasureColor48]
Measure=Calc
Formula=MeasureBand48*#ColorInt#

[MeasureColor49]
Measure=Calc
Formula=MeasureBand49*#ColorInt#

[MeasureColor50]
Measure=Calc
Formula=MeasureBand50*#ColorInt#

[MeasureColor51]
Measure=Calc
Formula=MeasureBand51*#ColorInt#

[MeasureColor52]
Measure=Calc
Formula=MeasureBand52*#ColorInt#

[MeasureColor53]
Measure=Calc
Formula=MeasureBand53*#ColorInt#

[MeasureColor54]
Measure=Calc
Formula=MeasureBand54*#ColorInt#

[MeasureColor55]
Measure=Calc
Formula=MeasureBand55*#ColorInt#

[MeasureColor56]
Measure=Calc
Formula=MeasureBand56*#ColorInt#

[MeasureColor57]
Measure=Calc
Formula=MeasureBand57*#ColorInt#

[MeasureColor58]
Measure=Calc
Formula=MeasureBand58*#ColorInt#

[MeasureColor59]
Measure=Calc
Formula=MeasureBand59*#ColorInt#


[MeasureColor50]
Measure=Calc
Formula=MeasureBand50*#ColorInt#

[MeasureColor51]
Measure=Calc
Formula=MeasureBand51*#ColorInt#

[MeasureColor52]
Measure=Calc
Formula=MeasureBand52*#ColorInt#

[MeasureColor53]
Measure=Calc
Formula=MeasureBand53*#ColorInt#

[MeasureColor54]
Measure=Calc
Formula=MeasureBand54*#ColorInt#

[MeasureColor55]
Measure=Calc
Formula=MeasureBand55*#ColorInt#

[MeasureColor56]
Measure=Calc
Formula=MeasureBand56*#ColorInt#

[MeasureColor57]
Measure=Calc
Formula=MeasureBand57*#ColorInt#

[MeasureColor58]
Measure=Calc
Formula=MeasureBand58*#ColorInt#

[MeasureColor59]
Measure=Calc
Formula=MeasureBand59*#ColorInt#

[MeasureColor60]
Measure=Calc
Formula=MeasureBand60*#ColorInt#

[MeasureColor61]
Measure=Calc
Formula=MeasureBand61*#ColorInt#

[MeasureColor62]
Measure=Calc
Formula=MeasureBand62*#ColorInt#

[MeasureColor63]
Measure=Calc
Formula=MeasureBand63*#ColorInt#

[MeasureColor64]
Measure=Calc
Formula=MeasureBand64*#ColorInt#

[MeasureColor65]
Measure=Calc
Formula=MeasureBand65*#ColorInt#

[MeasureColor66]
Measure=Calc
Formula=MeasureBand66*#ColorInt#

[MeasureColor67]
Measure=Calc
Formula=MeasureBand67*#ColorInt#

[MeasureColor68]
Measure=Calc
Formula=MeasureBand68*#ColorInt#

[MeasureColor69]
Measure=Calc
Formula=MeasureBand69*#ColorInt#

[MeasureColor70]
Measure=Calc
Formula=MeasureBand70*#ColorInt#

[MeasureColor71]
Measure=Calc
Formula=MeasureBand71*#ColorInt#

[MeasureColor72]
Measure=Calc
Formula=MeasureBand72*#ColorInt#

[MeasureColor73]
Measure=Calc
Formula=MeasureBand73*#ColorInt#

[MeasureColor74]
Measure=Calc
Formula=MeasureBand74*#ColorInt#

[MeasureColor75]
Measure=Calc
Formula=MeasureBand75*#ColorInt#

[MeasureColor76]
Measure=Calc
Formula=MeasureBand76*#ColorInt#

[MeasureColor77]
Measure=Calc
Formula=MeasureBand77*#ColorInt#

[MeasureColor78]
Measure=Calc
Formula=MeasureBand78*#ColorInt#

[MeasureColor79]
Measure=Calc
Formula=MeasureBand79*#ColorInt#

[MeasureColor80]
Measure=Calc
Formula=MeasureBand80*#ColorInt#

[MeasureColor81]
Measure=Calc
Formula=MeasureBand81*#ColorInt#

[MeasureColor82]
Measure=Calc
Formula=MeasureBand82*#ColorInt#

[MeasureColor83]
Measure=Calc
Formula=MeasureBand83*#ColorInt#

[MeasureColor84]
Measure=Calc
Formula=MeasureBand84*#ColorInt#

[MeasureColor85]
Measure=Calc
Formula=MeasureBand85*#ColorInt#

[MeasureColor86]
Measure=Calc
Formula=MeasureBand86*#ColorInt#

[MeasureColor87]
Measure=Calc
Formula=MeasureBand87*#ColorInt#

[MeasureColor88]
Measure=Calc
Formula=MeasureBand88*#ColorInt#

[MeasureColor89]
Measure=Calc
Formula=MeasureBand89*#ColorInt#

[MeasureColor90]
Measure=Calc
Formula=MeasureBand90*#ColorInt#



