;-----------------------------
;LEFT SIDE BARS
;-----------------------------


[MeterBand0]
Meter=Bar
MeasureName=MeasureBand0
X=#LXPos#
Y=#LYPos#
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand1]
Meter=Bar
MeasureName=MeasureBand1
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand2]
Meter=Bar
MeasureName=MeasureBand2
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand3]
Meter=Bar
MeasureName=MeasureBand3
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand4]
Meter=Bar
MeasureName=MeasureBand4
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand5]
Meter=Bar
MeasureName=MeasureBand5
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand6]
Meter=Bar
MeasureName=MeasureBand6
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand7]
Meter=Bar
MeasureName=MeasureBand7
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand8]
Meter=Bar
MeasureName=MeasureBand8
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


[MeterBand9]
Meter=Bar
MeasureName=MeasureBand9
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation1#
Flip=#SkinFlip#


;-----------------------------
;MIDDLE BARS
;-----------------------------


[MeterBand10]
Meter=Bar
MeasureName=MeasureBand10
X=#MXPos#
Y=#MYPos#
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand11]
Meter=Bar
MeasureName=MeasureBand11
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand12]
Meter=Bar
MeasureName=MeasureBand12
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand13]
Meter=Bar
MeasureName=MeasureBand13
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand14]
Meter=Bar
MeasureName=MeasureBand14
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand15]
Meter=Bar
MeasureName=MeasureBand15
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand16]
Meter=Bar
MeasureName=MeasureBand16
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand17]
Meter=Bar
MeasureName=MeasureBand17
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


[MeterBand18]
Meter=Bar
MeasureName=MeasureBand18
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)



[MeterBand19]
Meter=Bar
MeasureName=MeasureBand19
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
Flip=(1-#SkinFlip#)


;-----------------------------
;RIGHT SIDE BARS
;-----------------------------

[MeterBand20]
Meter=Bar
MeasureName=MeasureBand20
X=#RXPos#
Y=#RYPos#
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#


[MeterBand21]
Meter=Bar
MeasureName=MeasureBand21
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand22]
Meter=Bar
MeasureName=MeasureBand22
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand23]
Meter=Bar
MeasureName=MeasureBand23
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand24]
Meter=Bar
MeasureName=MeasureBand24
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand25]
Meter=Bar
MeasureName=MeasureBand25
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand26]
Meter=Bar
MeasureName=MeasureBand26
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand27]
Meter=Bar
MeasureName=MeasureBand27
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand28]
Meter=Bar
MeasureName=MeasureBand28
X=#BarSpace#R
Y=0r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#

[MeterBand29]
Meter=Bar
MeasureName=MeasureBand29
X=#BarSpace#R
Y=r
W=#Width#
H=#Height#
BarColor=#Color#
BarOrientation=Vertical
TransformationMatrix=#Orientation2#
Flip=#SkinFlip#





