[Variables]

;Color of details
AColor=255,255,255,200 

;Prefered music player ( AIMP, CAD, iTunes, MediaMonkey, MusicBee, Winamp, WMP, Spotify, WLM  )
Player=AIMP

;Lancher Program 1, 2 ,3
LP1=C:\Windows\explorer.exe
LP2=C:\Program Files (x86)\Mozilla Firefox\firefox.exe
LP3=C:\Program Files (x86)\#Player#\#Player#.exe

;Launcer Icons
LI1=#@#Images\GeoZ\9.png
LI2=#@#Images\GeoZ\10.png
LI3=#@#Images\GeoZ\38.png

;Deviant art link
DevURL=http://wyzzymoon.deviantart.com/art/TriSound-576149473


;---------------------------------------------------------------
;--------------------------------------------------------------

U=7
Spacing=1
UU=((2*#U#)+(1*#Spacing#))
UUU=((3*#U#)+(2*#Spacing#))
UUUU=((4*#U#)+(3*#Spacing#))
UUUUU=((5*#U#)+(4*#Spacing#))





